import type {
	Cart,
	Customer,
	LineItem,
	Order,
	Product,
	PublishedVariant,
	Store,
	User,
	Variant,
} from "@blazzing-app/validators/client";
import type { Collection } from "@blazzing-app/validators/server";

export const user: User = {
	authID: "Awdawd",
	avatar: null,
	createdAt: new Date().toISOString(),
	description: "AWdawd",
	email: "awdawd",
	fullName: "awdawd",
	id: "awedwa",
	metadata: {},
	phone: "awdaw",
	role: "moderator",
	updatedAt: new Date().toISOString(),
	username: "awdadw",
	version: 1,
};
export const cart: Cart = {
	id: "awd",
	billingAddressID: null,
	countryCode: "AU",
	createdAt: new Date().toISOString(),
	currencyCode: "AUD",
	email: "awdawd@gmail.com",
	fullName: "awd",
	phone: "wdaw",
	shippingAddressID: null,
	subtotal: 12,
	total: 12,
	updatedAt: new Date().toISOString(),
	userID: "awd",
	version: 1,
};

export const customer: Customer = {
	id: "adwW",
	createdAt: new Date().toISOString(),
	email: "awdwa",
	updatedAt: new Date().toISOString(),
	userID: "Awawd",
	version: 1,
	user,
};

export const store: Store = {
	id: "awda",
	countryCode: "AU",
	createdAt: new Date().toISOString(),
	currencyCodes: [],
	description: "adwaw",
	headerImage: null,
	image: null,
	name: "awdadwa",
	ownerID: "adw",
	updatedAt: new Date().toISOString(),
	version: 1,
};

export const variant: Variant = {
	optionValues: [],
	id: "daw",
	allowBackorder: true,
	barcode: "adwa",
	createdAt: new Date().toISOString(),
	description: "wahwr",
	discountable: true,
	handle: "hello world",
	height: 100,
	images: [],
	thumbnail: null,
	length: 100,
	material: "daw",
	metadata: {},
	originCountry: "AU",
	productID: "whatever",
	quantity: 2,
	sku: "2",
	title: "hello world",
	updatedAt: new Date().toISOString(),
	updatedBy: "what",
	version: 1,
	weight: 100,
	weightUnit: "g",
	width: 100,
	prices: [
		{
			id: "daw1",
			amount: 10,
			currencyCode: "AUD",
			variantID: "daw",
			version: 1,
		},
	],
};
export const product: Product = {
	id: "whatever",
	collectionID: "whatver1",
	createdAt: new Date().toISOString(),
	baseVariantID: "sef",
	metadata: {},
	score: 1,
	status: "draft",
	storeID: "awd",
	type: "physical",
	updatedAt: new Date().toISOString(),
	updatedBy: "noone",
	baseVariant: variant,
	version: 1,
	store,
	collection: {} as Collection,
	options: [],
	variants: [],
};
export const lineItem: LineItem = {
	cartID: "awdawd",
	createdAt: new Date().toISOString(),
	id: "adadw",
	orderID: "awdawdawd",
	productID: "awdad",
	quantity: 41,
	storeID: "aawfw",
	title: "awdawdaw",
	total: 12,
	updatedAt: new Date().toISOString(),
	variant: variant as PublishedVariant,
	variantID: "123",
	version: 1,
};

export const order: Order = {
	id: "order",
	billingAddressID: "adw",
	countryCode: "AU",
	createdAt: new Date().toISOString(),
	currencyCode: "AUD",
	customerID: "daw",
	email: "opachimari@gmail.com",
	fullName: "awdaw",
	items: [lineItem, { ...lineItem, id: "231" }],
	paymentStatus: "paid",
	phone: "adwawd",
	shippingAddressID: "awdaw",
	shippingStatus: "delivered",
	status: "cancelled",
	storeID: "awdaw",
	subtotal: 12,
	total: 12,
	updatedAt: new Date().toISOString(),
	version: 1,
};
