/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AccountID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BlazzingWorker": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "DatabaseURL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Email": {
      "sender": string
      "type": "sst.aws.Email"
    }
    "GoogleClientID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LivekitApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LivekitSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LivekitURL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WebUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
