import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

import base from "./base";

export default {
	content: base.content,
	presets: [base],
	theme: {
		container: {
			center: true,
			padding: "2rem",
			screens: {
				"2xl": "1400px",
			},
		},
		extend: {
			borderRadius: {
				lg: "var(--radius)",
				md: "calc(var(--radius) - 2px)",
				sm: "calc(var(--radius) - 4px)",
			},
			keyframes: {
				"accordion-down": {
					from: { height: "0" },
					to: { height: "var(--radix-accordion-content-height)" },
				},
				"accordion-up": {
					from: { height: "var(--radix-accordion-content-height)" },
					to: { height: "0" },
				},
				"caret-blink": {
					"0%,70%,100%": { opacity: "1" },
					"20%,50%": { opacity: "0" },
				},
			},
			animation: {
				"accordion-down": "accordion-down 0.2s ease-out",
				"accordion-up": "accordion-up 0.2s ease-out",
				"caret-blink": "caret-blink 1.25s ease-out infinite",
			},
			colors: {
				border: "var(--border)",
				input: "hsl(var(--input))",
				ring: "var(--ring)",
				background: "var(--background)",
				navbar: "var(--navbar)",
				component: "var(--component)",
				foreground: "hsl(var(--foreground))",
				primary: {
					DEFAULT: "hsl(var(--primary))",
					foreground: "hsl(var(--primary-foreground))",
				},
				secondary: {
					DEFAULT: "hsl(var(--secondary))",
					foreground: "hsl(var(--secondary-foreground))",
				},
				destructive: {
					DEFAULT: "hsl(var(--destructive))",
					foreground: "hsl(var(--destructive-foreground))",
				},
				muted: {
					DEFAULT: "hsl(var(--muted))",
					foreground: "hsl(var(--muted-foreground))",
				},
				popover: {
					DEFAULT: "hsl(var(--popover))",
					foreground: "hsl(var(--popover-foreground))",
				},
				card: {
					DEFAULT: "hsl(var(--card))",
					foreground: "hsl(var(--card-foreground))",
				},
				vice: {
					start: "#7C53FF",
					stop: "#F796FF",
				},

				  accent: {
					1: "var(--accent-1)",
					2: "var(--accent-2)",
					3: "var(--accent-3)",
					4: "var(--accent-4)",
					5: "var(--accent-5)",
					6: "var(--accent-6)",
					7: "var(--accent-7)",
					8: "var(--accent-8)",
					9: "var(--accent-9)",
					10: "var(--accent-10)",
					11: "var(--accent-11)",
					12: "var(--accent-12)",
				  },
				ruby: {
					1: "var(--ruby-1)",
					2: "var(--ruby-2)",
					3: "var(--ruby-3)",
					4: "var(--ruby-4)",
					5: "var(--ruby-5)",
					6: "var(--ruby-6)",
					7: "var(--ruby-7)",
					8: "var(--ruby-8)",
					9: "var(--ruby-9)",
					10: "var(--ruby-10)",
					11: "var(--ruby-11)",
					12: "var(--ruby-12)",
				  },
				  indigo: {
					1: "var(--indigo-1)",
					2: "var(--indigo-2)",
					3: "var(--indigo-3)",
					4: "var(--indigo-4)",
					5: "var(--indigo-5)",
					6: "var(--indigo-6)",
					7: "var(--indigo-7)",
					8: "var(--indigo-8)",
					9: "var(--indigo-9)",
					10: "var(--indigo-10)",
					11: "var(--indigo-11)",
					12: "var(--indigo-12)",
				  },
				  cyan: {
					1: "var(--cyan-1)",
					2: "var(--cyan-2)",
					3: "var(--cyan-3)",
					4: "var(--cyan-4)",
					5: "var(--cyan-5)",
					6: "var(--cyan-6)",
					7: "var(--cyan-7)",
					8: "var(--cyan-8)",
					9: "var(--cyan-9)",
					10: "var(--cyan-10)",
					11: "var(--cyan-11)",
					12: "var(--cyan-12)",
				  },
				  crimson: {
					1: "var(--crimson-1)",
					2: "var(--crimson-2)",
					3: "var(--crimson-3)",
					4: "var(--crimson-4)",
					5: "var(--crimson-5)",
					6: "var(--crimson-6)",
					7: "var(--crimson-7)",
					8: "var(--crimson-8)",
					9: "var(--crimson-9)",
					10: "var(--crimson-10)",
					11: "var(--crimson-11)",
					12: "var(--crimson-12)",
				  },
				  amber: {
					1: "var(--amber-1)",
					2: "var(--amber-2)",
					3: "var(--amber-3)",
					4: "var(--amber-4)",
					5: "var(--amber-5)",
					6: "var(--amber-6)",
					7: "var(--amber-7)",
					8: "var(--amber-8)",
					9: "var(--amber-9)",
					10: "var(--amber-10)",
					11: "var(--amber-11)",
					12: "var(--amber-12)",
				  },
				  blue: {
					1: "var(--blue-1)",
					2: "var(--blue-2)",
					3: "var(--blue-3)",
					4: "var(--blue-4)",
					5: "var(--blue-5)",
					6: "var(--blue-6)",
					7: "var(--blue-7)",
					8: "var(--blue-8)",
					9: "var(--blue-9)",
					10: "var(--blue-10)",
					11: "var(--blue-11)",
					12: "var(--blue-12)",
				  },
				  bronze: {
					1: "var(--bronze-1)",
					2: "var(--bronze-2)",
					3: "var(--bronze-3)",
					4: "var(--bronze-4)",
					5: "var(--bronze-5)",
					6: "var(--bronze-6)",
					7: "var(--bronze-7)",
					8: "var(--bronze-8)",
					9: "var(--bronze-9)",
					10: "var(--bronze-10)",
					11: "var(--bronze-11)",
					12: "var(--bronze-12)",
				  },
				  green: {
					1: "var(--green-1)",
					2: "var(--green-2)",
					3: "var(--green-3)",
					4: "var(--green-4)",
					5: "var(--green-5)",
					6: "var(--green-6)",
					7: "var(--green-7)",
					8: "var(--green-8)",
					9: "var(--green-9)",
					10: "var(--green-10)",
					11: "var(--green-11)",
					12: "var(--green-12)",
				  },
				  lime: {
					1: "var(--lime-1)",
					2: "var(--lime-2)",
					3: "var(--lime-3)",
					4: "var(--lime-4)",
					5: "var(--lime-5)",
					6: "var(--lime-6)",
					7: "var(--lime-7)",
					8: "var(--lime-8)",
					9: "var(--lime-9)",
					10: "var(--lime-10)",
					11: "var(--lime-11)",
					12: "var(--lime-12)",
				  },
				  orange: {
					1: "var(--orange-1)",
					2: "var(--orange-2)",
					3: "var(--orange-3)",
					4: "var(--orange-4)",
					5: "var(--orange-5)",
					6: "var(--orange-6)",
					7: "var(--orange-7)",
					8: "var(--orange-8)",
					9: "var(--orange-9)",
					10: "var(--orange-10)",
					11: "var(--orange-11)",
					12: "var(--orange-12)",
				  },
				  pink: {
					1: "var(--pink-1)",
					2: "var(--pink-2)",
					3: "var(--pink-3)",
					4: "var(--pink-4)",
					5: "var(--pink-5)",
					6: "var(--pink-6)",
					7: "var(--pink-7)",
					8: "var(--pink-8)",
					9: "var(--pink-9)",
					10: "var(--pink-10)",
					11: "var(--pink-11)",
					12: "var(--pink-12)",
				  },
				  violet: {
					1: "var(--violet-1)",
					2: "var(--violet-2)",
					3: "var(--violet-3)",
					4: "var(--violet-4)",
					5: "var(--violet-5)",
					6: "var(--violet-6)",
					7: "var(--violet-7)",
					8: "var(--violet-8)",
					9: "var(--violet-9)",
					10: "var(--violet-10)",
					11: "var(--violet-11)",
					12: "var(--violet-12)",
				  },

				  mauve: {
					1: "var(--mauve-1)",
					2: "var(--mauve-2)",
					3: "var(--mauve-3)",
					4: "var(--mauve-4)",
					5: "var(--mauve-5)",
					6: "var(--mauve-6)",
					7: "var(--mauve-7)",
					8: "var(--mauve-8)",
					9: "var(--mauve-9)",
					10: "var(--mauve-10)",
					11: "var(--mauve-11)",
					12: "var(--mauve-12)",
				  },

				  red: {
					1: "var(--red-1)",
					2: "var(--red-2)",
					3: "var(--red-3)",
					4: "var(--red-4)",
					5: "var(--red-5)",
					6: "var(--red-6)",
					7: "var(--red-7)",
					8: "var(--red-8)",
					9: "var(--red-9)",
					10: "var(--red-10)",
					11: "var(--red-11)",
					12: "var(--red-12)",
				  },

			},
		},
	},
	plugins: [animate],
} satisfies Config;
